### ISSUE TITLE
RFE: support more blkid identifiers

### ISSUE THREAD

**Issue by RPigott** [anatol/booster#1]
Booster currently supports identifying root fs with UUID, but it could be improved to use a variety of identifiers.

Looking around, systemd's fstab-generator [supports](https://github.com/systemd/systemd/blob/d1a61dfa69fe0f51feeb7d0ba752278eab367713/src/shared/fstab-util.c#L281-L297) LABEL, UUID, PARTUUID, and PARTLABEL. Support for those four would be great.

Linux also [supports](https://github.com/torvalds/linux/blob/3644e2d2dda78e21edd8f5415b6d7ab03f5f54f3/init/do_mounts.c#L254-L277) PARTUUID/PARTNROFF among others, which could be useful.

**Comment by medhefgo** [comment]
Also, paths from `/dev/disk/by-*` are also currently not supported, would be nice if it did.
