### ISSUE TITLE
Add extra files not working.

### ISSUE THREAD

**Issue by arun54321** [anatol/booster#106]
```
> cat /etc/booster.yaml
extra_files: busybox,fsck,fsck.f2fs,fsck.vfat
```
I regenerated initramfs using `/usr/lib/booster/regenerate_images` after editing the file, but resulting image doesn't have those files.

**Comment by anatol** [comment]
The config looks right and it should work.

Could you please generate the image locally as `booster` and then list content of the generated image as `lsinitcpio ./booster.img | grep fsck`?

**Comment by arun54321** [comment]
It works fine now. It didn't add files before because of file system problem. reinstalling Linux package fixed it.
