### ISSUE TITLE
lz4 compression causing kernel panic on boot

### ISSUE THREAD

**Issue by krathalan** [anatol/booster#117]
With the latest 5.15 kernel I am having an issue where only lz4 compression (not zstd) on the initramfs image is causing the following kernel panic:

```
initramfs unpacking failed: junk at the end of compressed archive
panic: initrd-release cannot be found

goroutine 1 [running]:
main.main()
    init/main.go:904 +0x9a
....
```

I noticed that the size of the lz4-compressed initramfs was 57MB. If I manually compressed the initramfs image after generation with lz4's highest compression levels, the lowest size was 60MB. So somewhere data is being lost. 

Additionally, I am only having this issue on one computer. My other computer is continuing to output working lz4-compressed initramfs images. The only difference between my two config files is that the one with the lz4 compression problem also includes the following modules: nvidia, nvidia_modeset, nvidia_drm, nvidia_uvm.

To be clear, this issue does not reproduce itself on a kernel version <= 5.14 or a different compression algorithm. I am only having this issue with kernel 5.15 and lz4 compression.

You can see my full config files here:
Broken lz4: https://github.com/krathalan/etc-config/blob/df12d69459fce70a86f22fd9ffdace8258c0aa5b/desktop/booster.yaml
Working lz4: https://github.com/krathalan/etc-config/blob/8b0dc210e341466f52e60f44fcf4c28b84a69a53/laptop/booster.yaml

**Comment by anatol** [comment]
Could you please check thew lz4 archive with `lz4 --test booster.img`?

Also check the recent booster changes from `wip` branch. Booster has moved to the newer lz4 library and might fix your situation.

> the one with the lz4 compression problem also includes the following modules: nvidia, nvidia_modeset, nvidia_drm, nvidia_uvm.

If you remove these modules does your machine able to read the initramfs image?

**Comment by darfrisk** [comment]
I seem to be having a similar issue and system will throw a kernel panic if I include the Nvidia modules within. If I remove the modules from the booster image the system boots up normally. 

I tried using Booster from the wip image however same error remains and system still unbootable.
If I run the command `lz4 --test booster.img` I get: **Error 53 : Decoding Failed ! Corrupted input detected !**

**Comment by anatol** [comment]
Could you please try `wip` branch, it uses newer version of lz4 library.

**Comment by darfrisk** [comment]
Had done that already as well, though still remained  with the same error

**Comment by anatol** [comment]
I can verify this problem with the latest lz4 library (v4.1.11).

```
lz4 --test test.img --verbose
*** LZ4 command line interface 64-bits v1.9.3, by Yann Collet ***
Stream followed by undecodable data at position 17712141 
test.img             : decoded 33554432 bytes      
```

@pierrec it looks like legacy writer produces some invalid output. It is still not clear what triggers it, maybe large size input. I will try to come up with a simple test case for the issue.

**Comment by anatol** [comment]
The upstream lz4 go library project is unresponsive with this issue and was not able to fix it unfortunately.

I replaced github.com/pierrec/lz4 library with a CLI wrapper. It shows that the LZ4 tests pass now (including tests for large images).

I pushed the fix to `replace-lz4-with-cli` branch. Please try it and let me know if you see any issues.
