### ISSUE TITLE
Add LVM volumes support

### ISSUE THREAD

**Issue by anatol** [anatol/booster#12]
Some users might need LVM volumes to construct root block device. We need to be able to handle it.

Here is how `dracut` configures LVM  https://mirrors.edge.kernel.org/pub/linux/utils/boot/dracut/dracut.html#_lvm

**Comment by ratorx** [comment]
You mentioned on Reddit that some use cases/setup examples would be helpful, so I thought I’d provide mine. 

I use LVM on LUKS so that I can have all my logical partitions (except boot) in 1 encrypted partition.

[Arch wiki link to setup](https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS)

**Comment by anatol** [comment]
Good news, everyone.

A preview version of LVM support has landed `wip` branch. It works with my test environment and I am interested to hear how well it works for you. Please test it if you have a change and share your experience.

To enable lvm please specify `enable_lvm: true` in the config file and regenerate the image.

**Comment by CarbonChauvinist** [comment]
Awesome, I can confirm that I can boot into my lvm volume now.
```
~ $ lsblk -f
NAME         FSTYPE      FSVER    LABEL UUID                                   FSAVAIL FSUSE% MOUNTPOINT
nvme0n1
├─nvme0n1p1  vfat        FAT32          58B8-7868                               894.6M    12% /boot
├─nvme0n1p2  LVM2_member LVM2 001       bdHyrn-FiMV-kDuo-4WIY-Wcje-Lo40-fkDY8Q
│ ├─nvg-root ext4        1.0            4d59661c-0a7e-41ce-8d7b-6cdb367f6e91     12.1G    70% /
│ └─nvg-home ext4        1.0            dfbfa78a-e802-42a8-ac80-bbbc155c4a8b     37.5G    64% /home
└─nvme0n1p3  swap        1              1c5bc919-96eb-49e4-abaf-a990b1452147                  [SWAP]

~ $ systemd-analyze
Startup finished in 9.826s (firmware) + 3.800s (loader) + 1.114s (kernel) + 311ms (initrd) + 1.661s (userspace) = 16.713s
graphical.target reached after 1.660s in userspace

```
I did have to enable universal flag otherwise boot appeared to hang after loading i915 module. Didn't look too much into it yet though as I just wanted to first confirm it booted.

**Comment by anatol** [comment]
It is really awesome to hear!!! Please test it as much as you can and report any issues you see.

> I did have to enable universal flag otherwise boot appeared to hang after loading i915 module. Didn't look too much into it yet though as I just wanted to first confirm it booted.

Enable `booster.debug` boot flag and report a bug with these logs.
