### ISSUE TITLE
error building booster images: provided key already used in mapping nvidia_drm

### ISSUE THREAD

**Issue by Brixus3** [anatol/booster#122]
I have both linux and linux-zen and their headers installed on arch linux. Lately I have only been able to build booster images for the zen kernel. During build this error is displayed but I haven't been able to track down what is causing this issue or how to fix it.

`provided key already used in mapping nvidia_drm->extramodules/nvidia-drm.ko.xz`

In the config file I have `modules_force_load: nvidia` but build still fails when I remove that line from the config.
In `/etc/modprobe.d/` I only have two files one for disabling watchdog and a sound driver. Nothing for nvidia.

**Comment by anatol** [comment]
`provided key already used in mapping` means that there are 2 module files that have the same name (`nvidia_drm`). The error message is too confusing. I changed the message to make it cleaner what exactly files have clashing names.

Please try `wip` branch. It will give you more information about clashing module files.

**Comment by Brixus3** [comment]
Thank you. I found the offending files and removed them. Builds fine now!
