### ISSUE TITLE
Provided key already used in mapping

### ISSUE THREAD

**Issue by ethindp** [anatol/booster#126]
For some reason I've started seeing this error occurring whenever I run the regeneration script or when I perform a system update. I'm not sure what's causing it and so when the regeneration fails pacman always falls back to mkinitcpio. I couldn't find any references about this problem... How do you resolve it?

**Comment by anatol** [comment]
Could you please provide exact command you are running and its error message?

**Comment by ethindp** [comment]
I'm running the standard regenerate_images command. The error is: 2022/01/27 20:02:49 provided key already used in mapping system76_acpi->kernel/drivers/platform/x86/system76_acpi.ko.zst

**Comment by anatol** [comment]
This error means there are 2 modules with the same name. Try booster from `master` branch, it will give you a cleaner error message (reference https://github.com/anatol/booster/commit/20da1446fb3cde7acb01789d535a705817d5552e).
