### ISSUE TITLE
module_force_load amdgpu not working with xz files

### ISSUE THREAD

**Issue by bgkillas** [anatol/booster#127]
on arch linux they transitioned to xz compresses linux firmware and now module_force_load: amdgpu fails running booster -debug seems to indicate it is looking for the non xz files and my system then fails to boot

**Comment by anatol** [comment]
I just ran `booster` at my machine and it completed successfully.

Could you please provide more information about the error? How to reproduce it and what exactly the error is.

**Comment by bgkillas** [comment]
test1 is without 'modules_force_load: amdgpu' in /etc/booster.yaml and test2 is with it in /etc/booster.yaml
[test1.txt](https://github.com/anatol/booster/files/7918723/test1.txt)
[test2.txt](https://github.com/anatol/booster/files/7918724/test2.txt)

**Comment by anatol** [comment]
Thanks. Now I see it. Here is the exact debug log info:

```
➜  booster booster --verbose build --force booster.img | grep amdgpu
activate module amdgpu
module amdgpu depends on firmware amdgpu/yellow_carp_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/vangogh_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/navi12_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/navi14_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/navi10_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/renoir_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/arcturus_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/raven2_gpu_info.bin but the firmware file does not exist
module amdgpu depends on firmware amdgpu/picasso_gpu_info.bin but the firmware file does not exist
```

Looking into it..

**Comment by anatol** [comment]
I pushed a fix for `wip` branch. Please try it and let me know if it works for you.

Once it is verified I'll patch the official `booster` package with the fix.

**Comment by bgkillas** [comment]
seems to be working thx

**Comment by anatol** [comment]
Thanks for the confirmation. I am going to patch `booster` package with it.

**Comment by anatol** [comment]
@bgkillas if you have a chance, could you please verify booster-0.7-2 package from [testing] repo?

**Comment by bgkillas** [comment]
oh your a trusted user cool that makes this alot nicer yes it does work
