### ISSUE TITLE
Booster forces load of crc32c_intel over crc32c_generic

### ISSUE THREAD

**Issue by nmeum** [anatol/booster#133]
I am currently trying to create a booster package for Alpine Linux. For this purpose, I am experimenting with Booster 0.7.0 in an Alpine x86_64 QEMU VM. In this VM my root filesystem is ext4 and ext4 is a kernel module on Alpine. Hence, I include ext4 in the image via `modules: ext4` in `/etc/booster.yaml`. My full config looks as follows:

```yaml
compression: gzip
modules: ext4

# enable emergency shell
extra_files: busybox

# mount timeout for debugging
mount_timeout: 10s
```

The generated image contains the following files:

```
lib -> /usr/lib
usr/
usr/local/
usr/local/lib -> /usr/lib
usr/sbin -> /usr/bin
bin -> /usr/bin
sbin -> /usr/bin
usr/local/bin -> /usr/bin
usr/local/sbin -> /usr/bin
var/
var/run -> /run
usr/lib64 -> /usr/lib
lib64 -> /usr/lib
usr/lib/
usr/lib/libc.musl-x86_64.so.1 -> ld-musl-x86_64.so.1
usr/lib/ld-musl-x86_64.so.1
lib/ld-musl-x86_64.so.1
init
usr/bin/
usr/bin/busybox
bin/busybox
lib/modules/
lib/modules/mbcache.ko
lib/modules/sd_mod.ko
lib/modules/crc32c_generic.ko
lib/modules/crc32c_intel.ko
lib/modules/jbd2.ko
lib/modules/crc16.ko
lib/modules/t10_pi.ko
lib/modules/ext4.ko
lib/modules/booster.alias
etc/
etc/booster.init.yaml
etc/initrd-release
```

However, with this image Booster is unable to mount the root filesystem. Further debugging revealed that this problem is caused by ext4's soft dependency on crc32c: 

```
$ modinfo ext4
filename:       /lib/modules/5.15.23-0-virt/kernel/fs/ext4/ext4.ko.gz
softdep:        pre: crc32c
license:        GPL
description:    Fourth Extended Filesystem
author:         Remy Card, Stephen Tweedie, Andrew Morton, Andreas Dilger, Theodore Ts'o and others
alias:          fs-ext4
alias:          ext3
alias:          fs-ext3
depends:        mbcache,jbd2,crc16
retpoline:      Y
intree:         Y
name:           ext4
vermagic:       5.15.23-0-lts SMP mod_unload modversions
```

I don't fully understand how it works on the kernel side of things, but `crc32c` seems to be provided by two modules: `crc32c_generic` and `crc32c_intel`. For ext4 to work, it seems to be required to load one of these before ext4 itself can be loaded. As you can see in the file listing above, the kernel modules for both are included in the image generated by Booster. During boot, Booster's `/init` seem to attempt loading `crc32c_intel` first(?). This doesn't work because my QEMU VM doesn't seem to support `crc32c_intel` thus [finit for this module fails](https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/arch/x86/crypto/crc32c-intel_glue.c#L225-L226).

Therefore, an error is raised in `loadModuleUnlocked`:

https://github.com/anatol/booster/blob/670a9467ff604b5f7a0a1f070174a5a7c033b217/init/module.go#L59-L62

due to this early return, the `wg.Wait()` in the `mountRootFs` function doesn't return:

https://github.com/anatol/booster/blob/670a9467ff604b5f7a0a1f070174a5a7c033b217/init/main.go#L258-L259

and therefore, I get a mount timeout, i.e. Booster fails to mount the root filesystem. If I modify `loadModuleUnlocked` to not return on finit errors and load `crc32c_generic` explicitly via `modules_force_load` in `/etc/booster.yaml` everything works as expected.

If my observations are correct, the solution for this problem is one of the following:

1. The `crc32_intel` finit failure should not be considered fatal by Booster's init (i.e. `wg.Done()` should be called for it).
2. Booster's ramdisk generator should only include `crc32c_generic`, not `crc32c_intel` in the image.

The latter is probably preferable.

**Comment by anatol** [comment]
Yeah softdependencies story needs to be clarified. I will need to read `insmod` code to understand what is the softdep logic. Especially when it comes to resolving aliased modules.

> crc32c seems to be provided by two modules: crc32c_generic and crc32c_intel.

Linux kernel aliases `crc32c` to both `crc32c_intel` and `crc32c_generic`:

```
$ grep crc32c modules.alias
alias crypto-crc32c-intel crc32c_intel
alias crc32c-intel crc32c_intel
alias crypto-crc32c crc32c_intel
alias crc32c crc32c_intel
alias cpu:type:x86,ven*fam*mod*:feature:*0094* crc32c_intel
alias crypto-crc32c-generic crc32c_generic
alias crc32c-generic crc32c_generic
alias crypto-crc32c crc32c_generic
alias crc32c crc32c_generic
```

so booster includes these both modules as it does not know which one will be needed at the boot time.

Do you create universal image? My guess yes, otherwise booster would only include modules you currently use at your host.

**Comment by anatol** [comment]
> I am not passing -universal but crc32c_intel doesn't show up in lsmod

then it sounds like a booster bug. I will check it.

**Comment by anatol** [comment]
I added possible fix to `wip` branch. @nmeum please check the branch and let me know if it makes any difference for you.

**Comment by nmeum** [comment]
Yes, with that patch applied crc32c_intel is no longer included in the image, only crc32c_generic. As such, it now boots fine in my QEMU VM.

Thanks a lot! :tada:

**Comment by anatol** [comment]
Thank you for the verification @nmeum!
