### ISSUE TITLE
about mounting efivars

### ISSUE THREAD

**Issue by dkwo** [anatol/booster#141]
This is more of a question than a bug, hopefully.
I'm trying to understand why, on my laptop runnig void linux, with booster as initram generator, I get
```
$ mount | grep efi
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
```
even though I do not mount efivars anywhere that I'm aware of, not in /etc/fstab,
and the init (runit) only mounts /sys, see https://github.com/void-linux/void-runit/blob/master/core-services/00-pseudofs.sh
`mountpoint -q /sys || mount -o nosuid,noexec,nodev -t sysfs sys /sys`
but not efivars (there's actually a PR there to do just this in void).

Could booster be affecting any of this?
The laptop is a thinkpad, and I also wonder whether Lenovo's uefi implementation has any role here,
since on another Dell machine with quite similar setup efivars are not mounted.

Thanks.

**Comment by anatol** [comment]
It is indeed the result of `booster` bootup.

It mount a number of fs - `/run` `/dev` `/proc` `/sys` and then *moves* it userspace.  It also mounts `efivarfs` just in case it is needed for partition autodiscovery, but it never unmounts it.

I am fine to unmount it in case it is not desirable to have it in user-space.

**Comment by dkwo** [comment]
Thanks, afaik it seems fine.
Is it correct that runit then picks up `efivarfs` when it mounts `/sys`?

**Comment by dkwo** [comment]
I guess the other machine, still running older booster-0.5_1, does not have efivars mounted as this feature was introduced later on in booster?

**Comment by dkwo** [comment]
Thanks for the prompt response.
I now understand how this works, and it seems totally fine to me.
