### ISSUE TITLE
Cannot boot with secure boot enabled.

### ISSUE THREAD

**Issue by arun54321** [anatol/booster#163]
```
booster: finit(crc32,generic): key was rejected by service 
booster: finit(crc32_pclmull: key was rejected by service 
booster: finit(lz4hc_compress): key was rejected by service 
booster: finit(lz4_compress): key was rejected by service 
booster: finit(video): key was rejected by service 
```
But kernel boots fine with dracut's initrd image. secure boot too works fine.

**Comment by anatol** [comment]
I would like to reproduce the problem locally.

What exactly instructions do you use:
 - for dracut?
 - for booster?

**Comment by arun54321** [comment]
for booster: `booster  build --force --kernel-version $(uname -a | awk '{ print $3 }')  /boot/booster-$(uname -a | awk '{ print $3 }').img` 

```
--- 
compression: zstd
modules: f2fs,i915
strip: true
universal: false
vconsole: false

```

dracut: default fedora dracut, created during kernel install.


I use refind as bootloader:
refind config:

```
menuentry "Fedora" {
	icon /EFI/refind/icons/os_fedora.png
	volume fb3b80c1-97b4-4de3-bc6b-93b7bdb9232a
	loader vmlinuz-5.18.9-200.fc36.x86_64
	initrd booster-5.18.9-200.fc36.x86_64.img
	options "initrd=ucode.img rw root=UUID=0f21968a-4fdd-45eb-b23f-d43c54a82960 psi=1 quiet rhgb sysrq_always_enabled=1"
	ostype Linux
	graphics on
}

menuentry "Fedora stock initrd" {
	icon /EFI/refind/icons/os_fedora.png
	volume fb3b80c1-97b4-4de3-bc6b-93b7bdb9232a
	loader vmlinuz-5.18.9-200.fc36.x86_64
	initrd initramfs-5.18.9-200.fc36.x86_64.img
	options "initrd=ucode.img rw root=UUID=0f21968a-4fdd-45eb-b23f-d43c54a82960 psi=1 quiet rhgb sysrq_always_enabled=1"
	ostype Linux
	graphics on
}
```

**Comment by anatol** [comment]
For booster please disable stripping `strip: false`.

**Comment by arun54321** [comment]
Okay. Is it necessary to not strip for secure boot?

**Comment by anatol** [comment]
It is not a secure boot, it is "signed modules". And you may not strip signed modules in booster (and neither dracut does).

Per kernel documentation https://www.kernel.org/doc/html/v5.18/admin-guide/module-signing.html

> Signed modules are BRITTLE as the signature is outside of the defined ELF container. Thus they MAY NOT be stripped once the signature is computed and attached. Note the entire module is the signed payload, including any and all debug information present at the time of signing.

**Comment by arun54321** [comment]
Yes. it works fine now. Thank you.
