### ISSUE TITLE
amd_pstate module not being used

### ISSUE THREAD

**Issue by JosefLitos** [anatol/booster#168]
I would like to try amd_pstate driver instead of acpi_cpufreq, but although it compiles successfully, the module isn't loaded, whereas with mkinitcpio it all works well.

**Comment by anatol** [comment]
Could you please provide more context for what you are doing? Logs, config files...

Did you try to force loading this module?

**Comment by anatol** [comment]
Also, prefer to use "Discussions" page for general questions https://github.com/anatol/booster/discussions

**Comment by JosefLitos** [comment]
config:
```yaml
modules: amdgpu,amd_pstate
extra_files: fsck,fsck.ext4
strip: true
```
kernel vmlinux extra params: `amd_pstate.shared_mem=1 initcall_blacklist=acpi_cpufreq_init`

The module works as expected when loaded manually after boot (`sudo modprobe amd_pstate`).
The issue seems to be it is not loaded by booster.

**Comment by anatol** [comment]
Try to move your modules to `modules_force_load:` section like this

```
modules_force_load: amdgpu,amd_pstate
extra_files: fsck,fsck.ext4
strip: true
```

**Comment by JosefLitos** [comment]
that did indeed fix the problem, do you know what could cause the normal loading not working?
