### ISSUE TITLE
'sbsign' complains about booster images: "Invalid DOS header magic"

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [anatol/booster#18]
Securing the initramfs via

```shell
/usr/bin/sbsign --key /etc/refind.d/keys/refind_local.key --cert /etc/refind.d/keys/refind_local.crt --output /boot/booster-linux.img /boot/booster-linux.img
```

returns Invalid DOS header magic

**Comment by joserebelo** [comment]
You are not supposed to sign the initramfs, you should package it into an Unified Kernel Image. See https://wiki.archlinux.org/index.php/Systemd-boot#Preparing_a_unified_kernel_image

**Comment by anatol** [comment]
Did anybody tried using booster with secureboot successfully? If it works then it would be great to mention it in the documentation.
