### ISSUE TITLE
Clevis unlock fails if Tang server requires DNS resolution

### ISSUE THREAD

**Issue by benalexau** [anatol/booster#19]
When a LUKS keyslot is configured with a command such as `clevis luks bind -d /dev/sda2 tang '{"url": "http://valid.dns.name"}'` a system boot displays "connect: cannot assign requested address 53" messages before requiring fallback LUKS console password entry.

This can be worked around by unbinding (`clevis luks unbind -d /dev/sda2 -s 1`) and re-binding with a numeric IP in the URL. In this case Booster successfully queried Tang and unlocked the partition (tested on Arch Linux).

It would be helpful to add DNS resolution to the project or mention it in the docs given those using something like network bound disk encryption probably have a local DNS server to resolve its name. :-)

In addition I found the network address does not `ping` and it might assist with troubleshooting if it would answer pings.

Thanks for your work on Booster.

**Comment by anatol** [comment]
@benalexau indeed DNS resolving does not work correctly at this point. We need to be able to configure DNS to make your use-case working.

We should be able to configure DNS it in one of these 2 ways:
* automatic using DHCP. DHCP Option with code == 6 supplies the list of DNS server.
* manual DNS configuration using `/etc/booster.yaml`

**Comment by anatol** [comment]
@benalexau I just pushed DNS support to `master` branch. Please pull the latest version of booster and let me know if you see any issues with it.
