### ISSUE TITLE
Cannot build initramfs on Pinebook Pro with 5.15.74 kernel

### ISSUE THREAD

**Issue by CameronNemo** [anatol/booster#192]
Hello, I am trying to use Booster on an aarch64 system, the rk3399-based Pinebook Pro, which is running a near-mainline kernel (the small number of patches are [here](https://github.com/CameronNemo/void-packages/tree/pbp-kernel-5.15/srcpkgs/pinebookpro-kernel/patches)).

I am getting this error:

```
2022/10/16 10:52:22 key arm_cci maps to multiple values (kernel/drivers/bus/arm-cci.ko,kernel/drivers/perf/arm-cci.ko)
```

I see this in my modules directory:

```
/usr/lib/modules/5.15.74_1/modules.builtin
141:kernel/drivers/bus/arm-cci.ko
588:kernel/drivers/perf/arm-cci.ko
```

Any tips on how to get this working? Do you need more information?

**Comment by anatol** [comment]
Booster generator finds 2 modules with the same name and it gets confused about which one to use.

Do you know how modprobe and other tools pick the right module at your system?

**Comment by anatol** [comment]
The kernel module dependency resolution is one of the weirdest things in linux kernel build system.

What I can do it to try to downgrade it from failure to a warning. `booster build` will report that there are several modules with the same name and continue image assembly. Hopefully, it will help with the situation.

**Comment by anatol** [comment]
@CameronNemo I pushed a possible fix to `wip` branch. Please try it and let me know if it makes any difference to you.
