### ISSUE TITLE
Booster breaks mouse input

### ISSUE THREAD

**Issue by junkmanner** [anatol/booster#206]
After installing booster on Void Linux (musl), it booted without issue. However, logging into either Xorg or Wayland, the mouse doesn't respond to any inputs. This happens with both universal and non-universal initramfs.

Moreover, the issue persists when building booster from source.

I also tried to use a different mouse, however this didn't solve the issue either.

**Comment by junkmanner** [comment]
Tested with master, and the issue is still present.
Oddly enough, I borrowed a random wireless logitech mouse from my friend, and that works without issue, however my Logitech G Pro wiresless doesn't.
Here is the booster log
[booster.log](https://github.com/anatol/booster/files/10724683/booster.log)

**Comment by anatol** [comment]
Interesting. Your mouse might require custom drivers.

Could you please try 2 things:
 - boot with booster (when the mouse does not work) and post content of `lsmod`
 - boot with working initramfs, when your mouse is OK and post `lsmod` again.

My guess is that the working configuration will have additional modules loaded. And booster might need to load it somehow as well.

**Comment by junkmanner** [comment]
Here is the output of lsmod.
The one where the mouse doesn't work is with booster, and the one where the mouse does work is with dracut
[lsmod-booster.log](https://github.com/anatol/booster/files/10725306/lsmod-booster.log)
[lsmod-dracut.log](https://github.com/anatol/booster/files/10725307/lsmod-dracut.log)
I am unsure what I should be looking for, but nothing seems particularly different.

**Comment by junkmanner** [comment]
Solved this by adding:
`modules_force_load: usbhid`
to my `booster.yaml`
Heres the booster log and output of lsmod with the mouse working if it can help debug this issue.
[booster.log](https://github.com/anatol/booster/files/10731660/booster.log)
[lsmod-booster-working.log](https://github.com/anatol/booster/files/10731683/lsmod-booster-working.log)

**Comment by anatol** [comment]
Thank you for debugging it. `usbhid` is not part of the default modules. Once I add it to the list `booster` will add the module to image automatically.
