### ISSUE TITLE
Unable to boot cryptsetup+btrfs with submodules

### ISSUE THREAD

**Issue by anatol** [anatol/booster#21]
Forking discussion off https://github.com/anatol/booster/issues/17

If fstab contains btrfs with subvolumes then there is some boot issue. `booster` itself seems fine, it detects rootfs, mounts it and launches `systemd`. But then `systemd` fails to boot properly.

cc @Th3Whit3Wolf

**Comment by anatol** [comment]
I confirm that I can reproduce this issue.

I hacked integration tests and added btrfs+subvolues testcase. It is available at `btrfs-subvolumes` branch.

Here is a log for 2 tests - with `linux` and `linux-lts` kernels. https://gist.github.com/anatol/21b56c1aa44f285c5f499c05e616aba3

**Comment by anatol** [comment]
One thing I spotted is that `genfstab` generates following options `subvolid=257,subvol=/@home,subvol=@home` that seems like duplicates. My understanding that there should be only one of the options.

**Comment by anatol** [comment]
The test fails because it waits until `/home` and `/srv` mountpoints are mounted but it never happens.

Logs shows that a disk was discovered:
```
dev-disk-by\x2duuid-724151bb\x2d84be\x2d493c\x2d8e32\x2d53e123c8351b.device: Changed dead -> plugged
dev-disk-by\x2did-scsi\x2d0QEMU_QEMU_HARDDISK_hd0.device: Changed dead -> plugged
dev-disk-by\x2dpath-pci\x2d0000:00:04.0\x2dscsi\x2d0:0:0:0.device: Changed dead -> plugged
dev-sda.device: Changed dead -> plugged
```
that corresponds to LUKS volume created with `cryptsetup luksFormat --uuid=724151bb-84be-493c-8e32-53e123c8351b`.

But it never gets to discovering unlocked btrfs disk with UUID `15700169-8c12-409d-8781-37afa98442a8`. I wonder why. The disk with such UUID is already unlocked by `booster` and I believe it is available at sysfs. Does systemd scan `/sys/block` at all?

**Comment by anatol** [comment]
I was wandering if mkinitcpio's `encrypt` hook passes some extra information about already unlocked volumes. But looking at its code here https://github.com/archlinux/svntogit-packages/blob/packages/cryptsetup/trunk/hooks-encrypt I do not see anything special. The hook essentially unlocks the volume the same way as we do.

**Comment by anatol** [comment]
So for some reason a crypt volume mounted with booster/luks.go is handled by systemd/udev differently than one mounted by cryptsetup.

Here is a root partition mounted by booster:

```
cat /run/udev/data/b254:0
I:4334941
E:DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E:DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E:DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E:SYSTEMD_READY=0
G:systemd
Q:systemd
V:1
```

and here is a test volume mounted by cryotsetup:
```
cat /run/udev/data/b254:1
S:disk/by-id/dm-uuid-CRYPT-LUKS2-a1fe17a28b174a648bd064ed31c0cd88-testcryptdevice
S:disk/by-uuid/bbcda4ae-b084-43c3-95d9-665ceb578f70
S:disk/by-id/dm-name-testcryptdevice
S:mapper/testcryptdevice
W:17
I:2635791712
E:DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E:DM_UDEV_PRIMARY_SOURCE_FLAG=1
E:DM_UDEV_RULES_VSN=2
E:DM_NAME=testcryptdevice
E:DM_UUID=CRYPT-LUKS2-a1fe17a28b174a648bd064ed31c0cd88-testcryptdevice
E:DM_SUSPENDED=0
E:ID_FS_UUID=bbcda4ae-b084-43c3-95d9-665ceb578f70
E:ID_FS_UUID_ENC=bbcda4ae-b084-43c3-95d9-665ceb578f70
E:ID_FS_VERSION=1.0
E:ID_FS_TYPE=ext4
E:ID_FS_USAGE=filesystem
G:systemd
Q:systemd
V:1
```

the latter has a bunch of extra fields. And among other things it confuses `lsblk`:
```
# the one mounted by booster, returns an empty string
$ lsblk -rno UUID /dev/mapper/luks-e922d09e-87a9-4a35-83f7-2592ef40cefa

# the one mounted by cryptsetup return UUID for underlying fs
$ lsblk -rno UUID /dev/mapper/testcryptdevice
bbcda4ae-b084-43c3-95d9-665ceb578f70
```

**Comment by anatol** [comment]
@Th3Whit3Wolf I believe your issue with btrfs+cryptmapper has been fixed. Could you please pull `master` and verify it?

**Comment by Th3Whit3Wolf** [comment]
It works!

**Comment by anatol** [comment]
yay, its awesome!

Thank you for the reproduce case scenario. It helped to debug the problem a lot.

**Comment by Th3Whit3Wolf** [comment]
I'm glad I could help! I hope to see this project in the official repos.

**Comment by anatol** [comment]
> I hope to see this project in the official repos.

Done https://archlinux.org/packages/extra/x86_64/booster/

**Comment by Th3Whit3Wolf** [comment]
That's awesome!
