### ISSUE TITLE
Incorrect kernel

### ISSUE THREAD

**Issue by kojq** [anatol/booster#230]
`booster` seems to detect the live environment's kernel instead of the one in chroot when doing `booster build booster-linux.img` (on Arch Linux). As a result, it cannot find the file.

**Comment by 5long** [comment]
I believe running `/usr/lib/booster/regenerate_images` should correctly detect kernels available in a chroot.

**Comment by kojq** [comment]
That would apply to all kernels present.

I would think it reasonable to perform the action for individual kernels

**Comment by anatol** [comment]
@kojq if you want to run `booster build` manually for a specific kernel then please specify `--kernel-version` parameter. See more information here https://man.archlinux.org/man/extra/booster/booster.1.en
