### ISSUE TITLE
booster fails when loading microcode image first

### ISSUE THREAD

**Issue by basploeger** [anatol/booster#251]
I am using Void Linux and have a microcode image file next to the booster initramfs like so:

```
/boot/intel-ucode.img
/boot/initramfs-6.6.11_1.img
```

`grub-mkconfig` automatically picks up the microcode image and generates lines like this in `/boot/grub/grub.cfg`:

```
initrd	/intel-ucode.img /initramfs-6.6.11_1.img
```

This should be a supported way of early loading CPU microcode before loading the initramfs. However, booster's init fails with exit code 71 and a message to press enter to reboot.

See also [here](https://wiki.archlinux.org/title/microcode#Early_loading) for background information.

**Comment by anatol** [comment]
Grub+Booster certainly works on Void, e.g. see report here https://github.com/anatol/booster/issues/29#issuecomment-1643635320

One way to debug your problem is to enable the booster debug logs and share it with us.

**Comment by basploeger** [comment]
I can confirm that Grub+Booster works on Void. It's the addition of the `intel-ucode.img` that triggers some bug in booster's init process.

I did a bunch of tests. The setup: I copied the standard Void Linux boot entry in `/boot/grub/grub.cfg`, then changed the `initrd` line to add the intel-ucode image, i.e.: `initrd   /intel-ucode.img /initramfs-6.6.11_1.img`. Then I added various kernel command line arguments in the same entry:

- If I add nothing, or add `booster.log=debug` or `booster.log=error,console` the error is triggered. All I can do is reboot. Sample screen output:
  ```
   [   3.772648] booster: exit status 71:
   Press ENTER to reboot
  ```
- If I add `booster.log=debug,console` or `booster.log=info,console` then it works. I get no error and the system boots normally.

I am not sure what this means. It seems the failure is somehow "bypassed" if (1) logging to console is enabled __and__ (2) booster actually logs some message to the console (i.e. logs are not empty). Note that in the case of `booster.log=error,console` nothing gets logged (because apparently there are no errors).

How can I share the logs with you in the failure case? All I can do at that point is reboot the laptop, at which point the logs are lost, right?

**Comment by basploeger** [comment]
The plot thickens.

If I disable `vconsole` in `/etc/booster.yaml` then all of the error cases above start working! So there's something fishy going on in combination with the vconsole. (And this fishiness can be avoided by logging stuff to it...).

For completeness, here are my configs:

__/etc/booster.yaml__
```
busybox: true
vconsole: false
enable_lvm: true
```

__/etc/vconsole.conf__
```
FONT=ter-u32n
KEYMAP=us
```

**Comment by anatol** [comment]
It sounds like https://github.com/anatol/booster/issues/234 then. See that issue, there was some debugging done there but not completely resolved yet.

**Comment by anatol** [comment]
https://github.com/anatol/booster/issues/234
