### ISSUE TITLE
Kernel panic when flash drive plugged in

### ISSUE THREAD

**Issue by Destroyer** [anatol/booster#274]
Crashed on first boot after PikaOS 4 installation. Left flash drive plugged in. The flash drive is causing a kernel panic (see screenshot), when removed I can boot without issues

```
    lsblk -S
    NAME HCTL       TYPE VENDOR   MODEL         REV SERIAL                    TRAN
    sda  12:0:0:0   disk Kingston DT Elite 3.0 1.01 0001A920542E9AC41B00000C2 usb

```
```
T:  Bus=05 Lev=01 Prnt=01 Port=11 Cnt=01 Dev#=  2 Spd=480  MxCh= 0

D:  Ver= 2.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1

P:  Vendor=0951 ProdID=168c Rev=01.00

S:  Manufacturer=Kingston

S:  Product=DT Elite 3.0

S:  SerialNumber=0001A920542E9AC41B00000C2

C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=400mA

I:  If#= 0 Alt= 0 #EPs= 2 Cls=08(stor.) Sub=06 Prot=50 Driver=usb-storage

E:  Ad=01(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms

E:  Ad=82(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
```

![booster](https://github.com/user-attachments/assets/3cf30649-2c53-4a74-90bb-bf60d2cb4204)

**Comment by anatol** [comment]
The problem happens here https://github.com/anatol/smart.go/blob/be6d7524480a17a9a44d73fb6cac1edb565cdf9c/scsi_linux.go#L127

It looks like `smart.go` unable to read the serial number from your device. Could you please re-file the bug to https://github.com/anatol/smart.go and we'll try to debug it there.

**Comment by Destroyer** [comment]
https://github.com/anatol/smart.go/issues/17
