### ISSUE TITLE
Detect f2fs filesystem properly

### ISSUE THREAD

**Issue by arun54321** [anatol/booster#28]
```
title   Arch Linux
linux   /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /booster.img
options root=PARTUUID=xxxxxxxxxxxxxxxxxxxxxx rootfstype=f2fs rw sysrq_always_enabled=1 quiet nowatchdog module_blacklist=iTCO_wdt mitigations=off  numa=off

```

**Comment by anatol** [comment]
Thanks for the report.

`PARUUID=XXX` is not supported at this point. See https://github.com/anatol/booster/issues/1

Is there any chance you can try either `UUID=XX` or `LABEL=XX` for time being?

**Comment by Froggy232** [comment]
Hi,
I use EfiBootMgr (so, direct boot) with root=UUID= and I have the exact same problem.
I use f2fs too, don't you think it's the cause?
Thanks for your work
Best regards

**Comment by anatol** [comment]
> I use f2fs too, don't you think it's the cause?

You are right. `f2fs` is not supported yet. It should be straightforward to add support for it. I will look at it.

**Comment by Froggy232** [comment]
Thanks you a lot, I will use it as soon as it support F2FS.

**Comment by anatol** [comment]
`booster-git` should support xfs now. Please take a look and let me know if you see any issues with it.

**Comment by arun54321** [comment]
> `booster-git` should support xfs now. Please take a look and let me know if you see any issues with it.

What about f2fs?

**Comment by ilyazzz** [comment]
> > `booster-git` should support xfs now. Please take a look and let me know if you see any issues with it.
> 
> What about f2fs?

Working properly for me.
