### ISSUE TITLE
RFE: add a way to exlucde modules from generated images

### ISSUE THREAD

**Issue by RPigott** [anatol/booster#3]
We can currently include extra modules with the "modules: " option in the config, but Booster could use a config option to exclude certain modules as well.

I would suggest a "modules-skip" or "modules-exclude" option for this purpose.

**Comment by oech3** [comment]
I want to readd module as below:
`modules-skip: kernel/`
`modules: btrfs`

**Comment by oech3** [comment]
or I want option to disable autodetect modules.

I think minimal and reproducible initramfs is not generated by excluding modules.
Because user may load unneeded ko accidently (by external storage).

**Comment by anatol** [comment]
A new "exclude" operator is added and it can be combined with `modules` elements. For example if one wants to exclude module foo then it will look like `modules: -foo` or exclude all modules is `modules: -*`.

Please try `master` and let me know if you see any issues.
