### ISSUE TITLE
Add fsck capability

### ISSUE THREAD

**Issue by libcg** [anatol/booster#32]
See https://wiki.archlinux.org/index.php/Fsck#Mechanism

**Comment by codicodi** [comment]
While compiling fsck into booster's init probably won't be easy, the 2nd, systemd based method listed in wiki appears to work just fine, as long as you pass `ro` kernel param

**Comment by anatol** [comment]
Implementing `fsck` in go is definitely overkill.

I think that `fsck` functionality should follow configuration similar to how the emergency shell is enabled. If user adds `fsck.<fs>` to the image (using `extra_files` config option) and root filesystem type matches the `<fs>` part then `fsck.<fs> /dev/...` is called before mounting it.

This feature implementation is straight-forward and should not take much time. Though I work on a few long-overdue code refactoring to make unit-testing easier. Once it is done I'll look to the `fsck`.

**Comment by codicodi** [comment]
Sounds good!
By the way, is there a reason not to mount read-only by default? That would make systemd's fsck work out of the box.

**Comment by anatol** [comment]
The only reason why booster mounts the root partition as RW by default is thats what `mount()` does if `mountflags` parameter is `0`. See https://man.archlinux.org/man/mount.2

If you want to mount it as read-only then pass `ro` with the kernel params.

**Comment by codicodi** [comment]
Yeah, I know how this works :)
I was just wondering whether changing the default wouldn't make user experience better.

**Comment by anatol** [comment]
Alright, `fsck` functionality is implemented now. Add `fsck,fsck.$YOURFS` to `extra_files` config option, regenerate the image and it should work.

This functionality is lightly tested. If you see any issues with it please let me know.

**Comment by anatol** [comment]
Booster does check `root` partition only. In your case you need `fsck,fsck.ext4` only.

`/boot` partition is used before initramf enters the game. In fact, this is the partition where the kernel and booster image reside. When booster is loaded it is too late to check `/boot`.
