### ISSUE TITLE
fails to boot if noatime in rootflags.

### ISSUE THREAD

**Issue by oech3** [anatol/booster#35]
Distro:Arch Linux
Version:booster-git

fails to boot if rootflags=noatime.
options section for systemd-boot is
`
options root=/dev/sda2 rw rootflags=subvol=@,compress=zstd,noatime quiet nowatchdog video=DP-1:e drm.edid_firmware=DP-1:edid/edid.bin random.trust_cpu=on`
If I remove noatime,It success to boot.and mounted with `/dev/sda2 on / type btrfs (rw,noatime,compress=zstd:3,space_cache,subvolid=1113,subvol=/@)` instead of relatime.
I think mount options is not changed since I use blank fstab.

`devAdd: cannot detect block type` message appears even sucseed to boot.

**Comment by anatol** [comment]
Thanks for the report.

It is indeed the issue with booster. It comes from the fact that `mount` function has 2 input flag parameters - integer `mountflags` and comma-separated list of strings `options` (see https://man.archlinux.org/man/mount.2). Some mount options needs to passed as mountflags. Booster needs to parse provided user options and separate mountflags from options.

For now the workaround is to drop `noatime`. It is passed to the mount() by default anyway.

**Comment by anatol** [comment]
Alright, this bug should be fixed now. Please install `booster-git` from AUR and let me know if you see any issues with it.
