### ISSUE TITLE
strip kernel modules

### ISSUE THREAD

**Issue by oech3** [anatol/booster#36]
initramfs size is reduced by stripping kernel modules.
mkinitcpio has strip hook.

**Comment by anatol** [comment]
Sounds like a good idea to decease size of the image.

And I think `strip` should be called for regular binaries as well.

**Comment by anatol** [comment]
I am looking at the `strip` [hook from mkinitcpio](https://github.com/archlinux/mkinitcpio/blob/master/install/strip) and it looks like stripping is *not* run for kernel modules. It is run for regular binaries and shared/static libraries only.

```shell
    find "$BUILDROOT" -type f -perm -u+w -print0 2>/dev/null | while read -d '' bin; do
        case $(file -bi "$bin") in
            *application/x-sharedlib*)
                # Libraries (.so)
                strip --strip-unneeded "$bin"
                ;;
            *application/x-archive*)
                # Libraries (.a)
                strip --strip-debug "$bin"
                ;;
            *application/x-executable*)
                # Binaries
                strip --strip-all "$bin"
                ;;
        esac
    done
```

**Comment by anatol** [comment]
So for kernel modules and shared libraries we need to use `--strip-unneeded` and for ELF binaries `--strip-all`. I have a change locally that seems work fine.

Stripping ELF binaries decreases size of the final image by about 10%. It is because Arch binaries already exclude debug symbols and there is not that much to strip.

**Comment by anatol** [comment]
The functionality is implemented at `master` branch. PTAL and let me know if you see any issues.
