### ISSUE TITLE
Can't boot system from encrypted partition

### ISSUE THREAD

**Issue by syntezoid** [anatol/booster#38]
Arch Linux
Booster-git
systemd-boot
system on cryptoluks (btrfs) with seperate boot partition (fat32) where are linux image and efi files.
A use rsync to copy whole system to non encrypted partition, and with recreate image, boot fine, but with encrypted it's always this:
![signal-2021-02-24-115901_002](https://user-images.githubusercontent.com/44477799/109132820-89ee8300-7754-11eb-9e46-c94080615b85.jpeg)

my /boot/loader/entries/arch.conf
```
title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /booster-linux.img
options rd.luks.name=ff64c852-9a56-ayd1-vf2d-072aff6652s0=arch root=/dev/mapper/arch
```

**Comment by anatol** [comment]
booster says that `/run` is absent at your root partition. `/run` is required by booster to mount a tmpfs with information about encrypted dm-crypt device.

* Could you please check if your image has an empty `/run` directory?
* Was you able to use this image with other initramfs (like dracut)?
* what is your `/etc/fstab`?

**Comment by syntezoid** [comment]
@anatol  Forgive me for not responding. I needed to get it right quickly, so I went back to Dracut.

This is strange, because I have two computers at work and one at home and one from work I must have encrypted (and the booster-git did not work on it), but on the other computer from work it works without any problems (except that this computer is unencrypted). All three computers use systemd-boot. Before going back to dracut in this computer from working with an encrypted disk, I tried installing GRUB and copied dracut-linux.img as initramfs-linux.img and initrafmfs-linux-fallback.img and the computer would boot up without any problem as in the picture. I don't like GRUB so I preferred to go back to dracut. I wasn't sure if it was a booster-git or systemd-boot problem. On the second, unencrypted computer, the booster-git had no problem with systemd-boot. I used dracut and systemd-boot on my computer at home and wanted to try booster-git now and there is a story similar to the one from work. It won't work with systemd-boot, but with GRUB it does. Picture below. This time, I stayed with GRUB with booster-git, but I don't know where problem lays.

![photo](https://user-images.githubusercontent.com/44477799/111564710-815cfb80-879a-11eb-9221-d7935ba0de6d.png)

For your questions:
1. I'm not suer how to check if my booster-linux.img have /run directory.
2. I'm not sure how to understand this.
3. my /etc/fstab

# /dev/sda1
UUID=A31B-E620      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro	0 2

```
# /dev/sda2 LABEL=homecomp
UUID=69bc4dd2-7f6c-4821-aa6b-d80d9c97d470	/         	btrfs     	rw,relatime,autodefrag,compress=zstd:2,space_cache,subvol=arch2	0 0

# /dev/sda2 LABEL=homecomp
UUID=69bc4dd2-7f6c-4821-aa6b-d80d9c97d470	/home     	btrfs     	rw,relatime,autodefrag,compress=zstd:2,space_cache,subvol=home	0 0

# /dev/sda2 LABEL=homecomp
UUID=69bc4dd2-7f6c-4821-aa6b-d80d9c97d470	/home/syntezoid/Torrents	btrfs     	rw,relatime,autodefrag,compress=zstd:2,space_cache,subvol=torrents	0 0
```

**Comment by anatol** [comment]
Booster says that the *mounted* rootfs does not contain neither `/run` nor `/sbin`. Are you sure that you mounted the correct device?

Could you please show me your systemd-boot config file? The one that contains the boot parameters. As well as output of `sudo lsblk -f`.

**Comment by syntezoid** [comment]
cat /boot/loader/entries/arch.conf
```
title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /booster-linux.img
options root=UUID=69bc4dd2-7f6c-4821-aa6b-d80d9c97d470 rw
```

sudo lsblk -f
```
NAME   FSTYPE FSVER LABEL        UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0
loop1
sda
├─sda1 vfat   FAT32              A31B-E620                             980.4M     4% /boot
└─sda2 btrfs        homecomp 69bc4dd2-7f6c-4821-aa6b-d80d9c97d470  713.9G    23% /home/syntezoid/Torrents
sr0
zram0                                                                                [SWAP]
zram1                                                                                [SWAP]
```

**Comment by anatol** [comment]
> cat /boot/loader/entries/arch.conf
> 
> ```
> title Arch Linux
> linux /vmlinuz-linux
> initrd /intel-ucode.img
> initrd /booster-linux.img
> options root=UUID=69bc4dd2-7f6c-4821-aa6b-d80d9c97d470 rw
> ```

You setup uses btrfs subvolumes. The root partition is mounted at subvolume `subvol=arch2` and you have to specify it in your boot config. Something like

 ```
title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /booster-linux.img
options root=UUID=69bc4dd2-7f6c-4821-aa6b-d80d9c97d470 rw rootflags=relatime,autodefrag,compress=zstd:2,space_cache,subvol=arch2
```

**Comment by syntezoid** [comment]
I'm an idiot ... You're absolutely right. Adding a value with the subvolume helped. Could you please add a note for stupid people like me to readme so they won't make my mistake in the future?

**Comment by anatol** [comment]
Feel free to update the documentation yourself. It is very easy to do, just click the "Edit" button on the file e.g. https://github.com/anatol/booster/edit/master/docs/manpage.md and github will create a PR.
