### ISSUE TITLE
Not booting quietly

### ISSUE THREAD

**Issue by medhefgo** [anatol/booster#39]
Despite having `quiet` in my kernel command line I get the following message twice during boot:

> devAdd: cannot detect block device type

Both are due to ntfs partitions (which booster does not support), but these messages should not be shown when booting quietly anyway.

**Comment by coxackie** [comment]
yes, I have also a bunch of
```
devAdd: cannot detect block device type
```
appearing upon boot. There are several windows partitions (for recoveries, etc.) that I presume are parsed. I do not see the point of these messages though.

**Comment by anatol** [comment]
This message says that some block device type was not recognized. This block device might contain the root filesystem user intends to mount. If booster unable to detect rootfs then the user should know why.

From other side I agree that it can be a bit annoying to print it for every unrecognized block device (e.g. like in case of ntfs).

So what I can do is to introduce 3 levels of messages:
* error, always printed
* warnings printed by default but can be disabled with `quiet` boot param
* debug, these are verbose messages from booster. Disabled by default but can be enabled with `booster.debug=1` boot param.

And then turn this `devAdd` message into a warning.

Yay or nay?

**Comment by medhefgo** [comment]
Sounds fine to me.

**Comment by coxackie** [comment]
it is ok I guess, but coming from `mkinitcpio` (as I am sure many will), this is quite weird - it never happened there, even without the `quiet` parameter. It will just confuse that something is really amiss...

**Comment by anatol** [comment]
Alright, the fix has been pushed to master.

Now booster respects `quiet` boot option. If the option is set then booster reduces verbosity of the output.

**Comment by eugene55** [comment]
Now it boots almost quietly, just prints capital G with a cursor. Can it be hid?

**Comment by anatol** [comment]
I use `quiet` boot param and I do not see any "G". For me the screen is empty until the login screen comes up.

I checked `init` code and I do not see any places where such thing can be printed (either with `fmt.Print*()` or with `severe()`.

Are you sure that it comes from booster? Can anyone else confirm it?

**Comment by eugene55** [comment]
It can be from console.go:118 ?
I start booster from directly from uefi so I guess it comes from booster itself

**Comment by anatol** [comment]
Do you have `vconsole` enabled?

**Comment by eugene55** [comment]
Yes, I have

**Comment by anatol** [comment]
I see the issue with `vconsole`. Thanks for reporting it.

**Comment by anatol** [comment]
Thank you @eugene55. The problem was the console escape sequence indeed. Hopefully it is fixed now.
