### ISSUE TITLE
Keymap not loaded.

### ISSUE THREAD

**Issue by giovannikraushaar** [anatol/booster#43]
Does not load the keymap specified in /etc/vconsole.conf. This is problematic in LUKS when combining password with special charcters and a non US keyboard.

Analogus are sd-vconsole in mkinitcpio and rd.vconsole in dracut.

**Comment by anatol** [comment]
Please try changes from `vconsole` branch. With it you can add `vconsole: true` to the config file to enable the early-user console configuration.

**Comment by giovannikraushaar** [comment]
Yes, that worked flawlessly. Thank you!
However I've noticed that (don't know if this is introduced in this version or was already there before) config does not default to /etc/booster.yml but has to be set through the appropriate flag.

**Comment by anatol** [comment]
> Yes, that worked flawlessly. Thank you!

Great to hear it!

> However I've noticed that (don't know if this is introduced in this version or was already there before) config does not default to /etc/booster.yml but has to be set through the appropriate flag.

booster's default config path is (and always was) `/etc/booster.yaml`.
