### ISSUE TITLE
Unrecoverable failure in required component org.gnome.Shell.desktop

### ISSUE THREAD

**Issue by coxackie** [anatol/booster#45]
Trying booster in Arch with zen kernel - no config files. The boot process hangs when trying to enter gnome shell. I get
```
gnome-session-binary[527]: Unrecoverable failure in required component org.gnome.Shell.desktop
```
in the journal. It does not happen when I use images from mkinitcpio. I can provide further info upon request.

EDIT: I realised that this is caused by not loading the amdgpu module. Same happens with mkinitcpio. However, if I include amdgpu to booster, it just does not boot.

**Comment by anatol** [comment]
One thing you can try is to add `amdgpu` firmware files manually. At `/etc/booster.yaml` add `extra_files: /usr/lib/firmware/amdgpu/`.

**Comment by anatol** [comment]
Filed a separate ticket to track the firmware files feature https://github.com/anatol/booster/issues/48

**Comment by coxackie** [comment]
One thing I certainly noticed is that, when adding amdgpu at mkinitcpio module, the size of the image increased quite a lot more than if I add it to booster. Maybe it is worth checking what mkinitcpio does...

**Comment by anatol** [comment]
`mkinitcpio` **does** add modules firmware. The #48 proposes adding this feature to booster. But before going forward with it I want to check that is the real culprit of your issue. Please let me know if `extra_files:` option from above makes any difference for you.

**Comment by oech3** [comment]
If Early KMS(including gpu ko in initramfs) solve it,gnome may running before gpu is initialized.see
[https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Xorg_fails_during_boot,_but_otherwise_starts_fine](url)
[https://superuser.com/questions/1469766/make-systemd-service-wait-for-a-device-generically](url)

**Comment by anatol** [comment]
thanks @oech3 I've see at wiki that some folks recommend adding the gpu drivers to initramfs but it was not clear for me why.

Anyway has anyone tried adding the firmware files to config? Or optionally try booster from master branch (`booster-git` AUR package) - it should add the dependent firmware files automatically. Let me know if it works or does not work for you.

**Comment by coxackie** [comment]
I added a couple of days ago `modules: amdgpu` and `extra_files: /usr/lib/firmware/amdgpu/`, but the result was the same, unfortunately: hang. You mean me to put `booster.debug=1` in the `options` part of the `conf` file (using `systemd-boot`). If yes, how do I capture the boot output later? Sorry for the noob questions, but at least I am willing to help...  :P

**Comment by anatol** [comment]
> but the result was the same, unfortunately: hang

bummer.

Try to add `debug booster.debug=1` boot parameters. Is there anything interesting in the logs?

> If yes, how do I capture the boot output later?

Using your phone camera is probably the easiest way.

Is there a way to reproduce this problem with Nvidia GPU? So I can try to do play with it locally.

**Comment by oech3** [comment]
@coxackie can you boot if you disable gdm.service ?
If it boot,does `systemctl start gdm` work after waiting 10s?

**Comment by coxackie** [comment]
@oech3 I will check, but I am pretty sure this is not the issue (when I use `amdgpu`). It hangs from the very beginning.

 To be honest, I would not like to use the `amdgpu` module. If I do not, for some reason `org.gnome.Shell.desktop` has a problem, but if I change tty with Ctrl-Alt-F2 and then go back immediately with Ctrl-Alt-F1, the gnome login screen appears. It is ridiculous, but in all honesty I prefer this than putting all the amd files in the image, as it increases the size a lot, and there is not so much space in the partition (dual booting).

**Comment by anatol** [comment]
I added `modules: nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm` to my config and tried to boot with this image. I found that `umount(/sys)` fails with EBUSY that means some driver (nvidia?) still uses it. I unmount it lazily and now my problem is gone. Now I can boot my machines with `nvidia` drivers added to the image.

I pushed https://github.com/anatol/booster/commit/82feb9111f7acb9d2563d2b04b9feab3777a9772 to master. Is there any chance you can try to boot with it?

**Comment by coxackie** [comment]
Sorry for being delayed in answering - I will try it again when a new version comes out, and then let you know here what is going on.

**Comment by anatol** [comment]
Thanks!

Try `master` branch - it contains a change that adds firmware files automatically. It might help in your situation.

**Comment by CyberX5** [comment]
Hi,

I dont think this is fixed, specifically adding `amdgpu` to `modules:` or `modules_force_load:` does not boot.

Using `-universal` doesn't appear to change anything, adding `extra_files: /usr/lib/firmware/amdgpu/` doesn't ether, im using `booster.disable_concurrent_module_loading`.

The output with `booster.debug` just freezes at `loading module amdgpu`.

Heres the output of `booster -kernelVersion 5.12.12-arch1-1 -debug -force -universal -output /boot/booster-linux.img` [file.txt](https://github.com/anatol/booster/files/6683661/file.txt)

If i can help somehow feel free to tell me :slightly_smiling_face:.

**Comment by coxackie** [comment]
Sorry for the huge delay between my responses. Turns out that `org.gnome.Shell.desktop` is not perfectly fine without specifying the module, so I do not have to deal with it anymore, and I am happy - size becomes quite smaller.

**Comment by anatol** [comment]
There are some fixes at `wip` branch that might help with this issue. If you have a chance please pull the `wip` branch and check whether this issue is fixed or now.

**Comment by CyberX5** [comment]
Its fixed, adding `amdgpu` to `modules:` or `modules_force_load:` works. Didnt need to do anything else.

Thank you 🙂.
