### ISSUE TITLE
Booster should look at the installed kernels modules not the booted kernels modules

### ISSUE THREAD

**Issue by advaithm** [anatol/booster#46]
Currently I'm facing the issue where my kernel booted on the arch linux iso is old and the standard Linux kernel. On my install it shows up as the old regular kernel but I've installed the zen kernel on my system.

**Comment by anatol** [comment]
By default booster creates initramfs for current kernel as reported by `uname -r`. If you want to change it please use `-kernelVersion` flag. Please see `man booster` for additional information about booster config/arguments.

Also note that Arch's install hook generates images for all **installed** kernels.
