### ISSUE TITLE
Initramfs with root partition using lvm and luks encryption fails to boot as its looking for a nonexistent kernel module 

### ISSUE THREAD

**Issue by Lunarequest** [anatol/booster#47]
I'm trying to install arch linux using luks with lvm and booster for the initramfs. On boot I get the following error `/usr/lib/modules/5.11.4-arch1-1/luks.ko` I've had similar errors with both the lts and zen kernels as well.

Any idea why I get these errors and how to fix them?

**Comment by anatol** [comment]
There is no such module as `luks.ko`.

What is config file you use?

**Comment by advaithm** [comment]
```yml
universal: false
strip: true
compression: zstd
```

**Comment by anatol** [comment]
It is really weird then. Please post the full output of `booster -debug`. Also add `booster.debug=1` to the boot parameter and share the boot output with me (e.g. using a photo camera).

**Comment by anatol** [comment]
Also post your `lsmod`.

**Comment by anatol** [comment]
I see it now. It looks like you specified luks' UUID as a root. And it is wrong. You should specify UUID of a filesystem that sits on top of LUKS partition. That top filetype should be have type like `ext4`, `btrfs`, ...

TODO: booster should provide a more helpful and actionable error message for such situation.

**Comment by advaithm** [comment]
What's the variable I should use to pass through the fstype?

**Comment by anatol** [comment]
> What's the variable I should use to pass through the fstype?

Per `man booster`:

> rootfstype=$TYPE  (e.g. rootfstype=ext4). By default booster tries to detect the root filesystem type. But if the autodetection does not work then this kernel parameter is useful. 

But booster will detect filesystem type automatically.

In your case the problem that you specified wrong `root=` boot parameter.

**Comment by advaithm** [comment]
So `root=/dev/mapper/device` right?

**Comment by anatol** [comment]
> So `root=/dev/mapper/device` right?

I do not know. It depends on your configuration.

Post your `lsblk` and the boot parameters.

**Comment by advaithm** [comment]
sorry I took so long to send these but I had some irl stuff
lsblk
![IMG_20210311_140148](https://user-images.githubusercontent.com/30698906/110759176-555de980-8273-11eb-8e51-598b57985a0e.jpg)
blkid
![IMG_20210311_141217](https://user-images.githubusercontent.com/30698906/110760393-ac17f300-8274-11eb-92ad-402583a30535.jpg)
boot options
![IMG_20210311_141310](https://user-images.githubusercontent.com/30698906/110760421-b4702e00-8274-11eb-98a1-f2da7639205c.jpg)

**Comment by anatol** [comment]
In your bootloader config:
1. you don't need `cryptdevice` parameter
2. instead of `rd.luks.uuid` you need to use `rd.luks.name=$UUID=cryptroot` this will open a partition with this $UUID as `/dev/mapper/cryptroot`
3. the partition where the LUKS resides is `/dev/sda2` and its UUID is `ead379.....`. It means the luks parameter will be `rd.luks.name=ead37914-21<....>=cryptroot`.

**Comment by advaithm** [comment]
I do get a password prompt now but on entering the correct password I get
![IMG_20210311_225407.jpg](https://user-images.githubusercontent.com/30698906/110828119-bbbb2a00-82bc-11eb-9749-769b86ef7696.jpg)

**Comment by advaithm** [comment]
Wait it kernel panicked ![IMG_20210311_225902.jpg](https://user-images.githubusercontent.com/30698906/110828777-67647a00-82bd-11eb-8949-0c4200f14716.jpg)

**Comment by anatol** [comment]
The kernel panic is expected and the result of timeout.

The real culprit is "Error allocating crypto tfm" that I am not sure where it comes from. Try to add "debug" to the boot parameters. It might provide more information about what is going on.

**Comment by anatol** [comment]
The problem might be due to some extra cryptographic modules are missing in initramfs.

As a workaround for it you can try to add 'universal: true` to you config file and regenerate the images.

**Comment by anatol** [comment]
And also show me the output of `sudo cryptsetup luksDump /dev/sda2 | grep -i ciph` that will geve more information about what cipher do you use for your LUKS device.

**Comment by advaithm** [comment]
![IMG_20210311_234138.jpg](https://user-images.githubusercontent.com/30698906/110834323-6b939600-82c3-11eb-8f88-1964361c3fa5.jpg)

**Comment by anatol** [comment]
The ciphers look fine (these are default versions) and it should work.

Anyway try to use `universal: true` images.

**Comment by advaithm** [comment]
Tried that didn't do anything different here is the output with booster.debug=1![IMG_20210311_235524.jpg](https://user-images.githubusercontent.com/30698906/110835846-5586d500-82c5-11eb-8b63-a118536fbfb9.jpg)

**Comment by anatol** [comment]
It is still the same "error allocating crypt tfm" problem. Try also adding `debug` boot parameter for more logs from the kernel itself.

Also post your `cat /proc/crypto`.

**Comment by advaithm** [comment]
out put of `cat /proc/crypto` https://pastebin.com/mPeqtivH

**Comment by anatol** [comment]
Thanks for sharing it. All modules used by your crypto subsystem are part of the `universal` booster image. I do not see how your booster unable to initialize crypto.

**Comment by advaithm** [comment]
shall I try reinstalling?

**Comment by anatol** [comment]
Try with the default config file (i.e. empty /etc/booster.yaml) and install booster-git from AUR.
