### ISSUE TITLE
PKGBUILD:add -buildid= to -ldflags= for reducing bin size

### ISSUE THREAD

**Issue by oech3** [anatol/booster#52]
Binary size is reduced by adding -ldflags=-buildid= to PKGBUILD.
and it is needed for reploducible build.

**Comment by anatol** [comment]
where did you get this information from? I am looking at the wiki page https://wiki.archlinux.org/index.php/Go_package_guidelines and do not see any references to `-buildid` flag.

**Comment by oech3** [comment]
https://github.com/golang/go/issues/34186
Sorry,BuildID does not depend on filepath where did I build in my test now.
I leave this issue for reducing bin size.

You can checy BuildID by `file /usr/lib/booster/init`

**Comment by anatol** [comment]
And how much size this going to be saved if this flag is used?

**Comment by oech3** [comment]
under 100 byte.
If it is not related to reploduciblity and there is a reason to remain ID,close this.
