### ISSUE TITLE
Systemd integration

### ISSUE THREAD

**Issue by travankor** [anatol/booster#53]
Is there a way to keep systemd integration optional? I know that Arch uses systemd, but not all distros have it available.

This would enable popular distros like Alpine and Void that target musl libc to work with booster.

**Comment by anatol** [comment]
Hi @travankor what makes you believe that booster depends on systems?

**Comment by travankor** [comment]
Some of the tests calls various parts of systemd. vconsole setting is systemd specific, and rd.luks is from systemd (`/etc/crypttab` is not needed without systemd).

Basically, I just wanted to know if deep systemd integration (like dracut) was a goal of this project before trying to package it.

**Comment by anatol** [comment]
vconsole feature only parses a simple config file `/etc/vconsole.conf` and does not depend on any systemd libraries/binaries. Besides that vconsole feature is optional and disabled by default.

`rd.luks.uuid` and `rd.luks.name` are kernel boot parameters parsed by booster. There is nothing systemd-specific here.

`booster` reports initrd boot time to systemd *if* it detects that the userspace init is systemd. But that's the only systemd-specific functionality in booster.

Neither booster generator part nor init require systemd. Booster created with size and speed in mind tries to avoid pulling heavy dependencies into initramfs.

**Comment by travankor** [comment]
Thanks for the info, that's exactly what I hoped to hear.

I started packaging it for Void https://github.com/void-linux/void-packages/pull/29434, but ran into some issues with cross-compilation. Why are link flags used in the Arch package if booster is pure go (no-cgo)?

trying to cross-compile from `amd64` to `aarch64`:
```
GOROOT_FINAL='go' /usr/lib/go/pkg/tool/linux_amd64/link -o $WORK/b174/exe/a.out -importcfg $WORK/b174/importcfg.link -installsuffix shared -buildmode=pie -buildid=l2Eoaz8H2SucTtvXbHwD/RsG2bOKgeDgkwLJczQUX/AdZfReeh3lt371ZOCKbG/l2Eoaz8H2SucTtvXbHwD -linkmode external -extldflags -extld=aarch64-linux-musl-gcc /host/gocache-muslc/40/40ba9f9f24f3397342134227eca07d55f76116e69853a816fefd545231a82fdf-d
# github.com/anatol/booster/generator
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-994768235/go.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

**Comment by anatol** [comment]
> I started packaging it for Void [void-linux/void-packages#29434](https://github.com/void-linux/void-packages/pull/29434), but ran into some issues with cross-compilation. Why are link flags used in the Arch package if booster is pure go (no-cgo)?

Arch package uses the standard guidelines https://wiki.archlinux.org/index.php/Go_package_guidelines

But as Arch is x86 centric I am not sure that these flags were tested with cross compilation.

**Comment by anatol** [comment]
Closing this ticket as the original question is resolved

**Comment by rieje** [comment]
> `rd.luks.uuid` and `rd.luks.name` are kernel boot parameters parsed by booster. There is nothing systemd-specific here.

To clarify, `cryptdevice=UUID=xxxxxxx:cryptroot:allow-discards` are also (non-systemd) kernel boot parameters parsed by booster just like `rd.luks.options=discard`? Or is there a need to convert it to sd-encrypt equivalent (systemd hook) syntax `rd.luks.name=xxxxxxx:cryptroot rd.luks.options=discard`? 

Only the `rd.`* options are mentioned in the manpage.
