### ISSUE TITLE
can not omit file path of modules.

### ISSUE THREAD

**Issue by oech3** [anatol/booster#56]
`modules: kernel/drivers/hid/hid-apple.ko.xz` in booster.yaml work.
but
`modules: hid-apple`
`modules: hid-apple.ko.xz`
`modules: kernel/drivers/hid/hid-apple.ko`
fails.

I want to omit .xz at least.
Because ko in package may compressed with other format in the future.

`modules: ntfs3,exfat` is possible.

**Comment by oech3** [comment]
kernel/drivers/hid is not in
https://github.com/anatol/booster/blob/6bdf45b08df4078a2d7d13e63e81623d4f02462d/generator/generator.go#L64-L77
is it related?

**Comment by anatol** [comment]
Linux kernel modules naming is a bit confusing. The module filenames use dash symbol ("-") while the module names use underscore ("_"). So `modules: hid_apple` should work for you.

All filenames use module directory as a starting point. `modules: hid-apple.ko.xz` this is going to work only if the fie is in root of the tree e.g. `/usr/lib/modules/5.11.6-arch1-1/hid-apple.ko.xz`

> I want to omit .xz at least. Because ko in package may compressed with other format in the future.

I makes sense, will look at it.

> kernel/drivers/hid is not in the list

Currently this directory is not in the filter list but it can be added if it is really needed. It needs a rationale though. Are `kernel/drivers/hid` for keyboard drivers primarily?

**Comment by oech3** [comment]
Thankyou.`modules: hid_apple` worked.
Would you add to document about

> The module filenames use dash symbol ("-") while the module names use underscore ("_").
I need hid_apple to use my keyboard.

**Comment by anatol** [comment]
> Would you add to document about

Feel free to update the documentation yourself. It is very easy to do, just click the "Edit" button on the file e.g. https://github.com/anatol/booster/edit/master/docs/manpage.md anf github will create a PR.
