### ISSUE TITLE
allow disabling module autodetection

### ISSUE THREAD

**Issue by oech3** [anatol/booster#59]
booster autodetects modules required for booting and add them to image now.
I request config for disabling module autodetection.It is useful if user know every ko needed for booting.

Similar issue is opened at #3.
But disabling autodetection is different from #3.Because I may load exfat.ko before generating image.
It is difficult to notice I can exclude exfat by `lsinitcpio /boot/booster-linux.img`. Because it is not added to image always.

I think disabling module autodetection is easier from #3.and #3 is not needed.

If you think this issue is same for #3,close this issue.

**Comment by anatol** [comment]
It is the same as #3.

I have a change sitting in my local testing branch. It adds new operators `-` (minus sign) to remove modules and `*` (star) as an alias for "all modules". Using it would be possible to do for example `modules: -*,ext4` that removes all predefined modules and adds only `ext4`.
