### ISSUE TITLE
Arch Linux:Unneeded img remain after uninstalling kernel

### ISSUE THREAD

**Issue by oech3** [anatol/booster#72]
Step to reproduce:
1. Install `linux-lts`
2. Uninstall `linux-lts`
3. `ls /boot|grep lts`

**Comment by anatol** [comment]
Do `mkinitcpio` and `dractut` also remove its generated files?

**Comment by oech3** [comment]
> Do mkinitcpio and dractut also remove its generated files?

Yes with mkinitcpio

**Comment by anatol** [comment]
Alright, it looks like it is coming from this hook https://github.com/archlinux/mkinitcpio/blob/master/libalpm/hooks/60-mkinitcpio-remove.hook that calls this script https://github.com/archlinux/mkinitcpio/blob/master/libalpm/scripts/mkinitcpio-remove

Booster needs an equivalent for it.

**Comment by oech3** [comment]
Same for vmlinuz .
It seems `dracut` does not have pacman hooks.

I think kernel package should have blank `/boot/vmlinuz-$pkgbase`
and have hook operate `cp /usr/lib/modules/VER/vmlinuz /boot/vmlinuz-$pkgbase`.
and `/boot/vmlinuz-$pkgbase` is managed by pacman.

initramfs generator only need to have hook for generating(cleaning) img.

**Comment by Sporif** [comment]
I have a dracut install/remove hook that can be adapted for use with booster

https://github.com/Sporif/dracut-hook
