### ISSUE TITLE
Failed to open pthread

### ISSUE THREAD

**Issue by travankor** [anatol/booster#81]
On a luk2 system, I can't boot with the initramfs and get failed to open pthread library error. I think this is luk2 format related since mkinitcpio had a similar pthread warning for luk2 format before mkinitcpio was patched.

**Comment by anatol** [comment]
`init` binary used at the build time is a static ELF and is not linked to pthread or any other dynamic library.

Here is how it looks at Arch Linux:
```
$ ldd /usr/lib/booster/init 
	not a dynamic executable
```

Do you compile booster for void? How do you do it? You probably want to look at the Arch build instructions https://github.com/archlinux/svntogit-packages/blob/packages/booster/trunk/PKGBUILD

**Comment by travankor** [comment]
On glibc, `init` binary wasn't static without `-extldflags "-static"`. On musl, I think `init` didn't need this.

Now, it says failed top open `/usr/lib/modules/cbc.ko` for decryption. The kernel only has `pcbc.ko` and `xcbc.ko` and this works for decrypting on other initramfs.

**Comment by anatol** [comment]
> Now, it says failed top open `/usr/lib/modules/cbc.ko` for decryption. The kernel only has the modules `pcbc.ko` and `xcbc.ko` and this works for decrypting on other initramfs.

Do you have `cbc` module compiled-in?

**Comment by travankor** [comment]
>Do you have cbc module compiled-in?

Yes, it's not built as a module`CONFIG_CRYPTO_CBC=y`

**Comment by anatol** [comment]
Could you please patch-in following change and see if it makes a difference for you? https://github.com/anatol/booster/commit/e85ea7386f456afaa4f646e21c3407e39bb61bb4

**Comment by travankor** [comment]
Yes, that works. Now there is one more error: `Unkown af hash algorithm: sha-512`.

**Comment by anatol** [comment]
I am looking at the list of hash algorithm names supported by `cryptsetup` and I do not see `sha512` there. There are `sha3-512` and `sha512` algos defined.

How did you initialize your LUKS partition? What the exact `cryptsetup` command?

**Comment by travankor** [comment]
`cryptsetup luksFormat -v --hash sha512 --use-random /dev/sdx`

**Comment by anatol** [comment]
The name of the hash function is `sha512` not `sha-512`. I see you changed the comment to specify the correct hash name.

I just added `sha512` support to luks.go. Could you please either pull the latest https://github.com/anatol/luks.go or booster's `wip` page.

**Comment by travankor** [comment]
Thanks, everything works so far. I think `sha512` applies to luks1 as well.

**Comment by anatol** [comment]
> Thanks, everything works so far. I think `sha512` applies to luks1 as well.

Great to hear it fixes the issues. Does `booster` work fine now?

Good point about LUKS1, I'll add it there as well.
