### ISSUE TITLE
poweroff issue with stripping i915 from linux 5.12

### ISSUE THREAD

**Issue by oech3** [anatol/booster#86]
I can't poweroff a PC with i915 chip at the same time as https://bugs.archlinux.org/task/70773?project=1&string=linux was reported(but it is about suspend).
It occur if  `*bug_table` is stripped from `i915.ko`.Stripping other is OK.
Some people reports FS#70773 is solved with 5.12.7 .But I can't solve with upgrading.

I can't understand why stripping `*bug_table` is bad.

If it is not bug of `i915`,`booster` shouldn't `*bug_table` for early KMS.

**Comment by anatol** [comment]
Just to confirm - do you see this problem with 5.12.8 if and only if `strip` option is enabled?

**Comment by oech3** [comment]
Yes.
Poweroff fails with `modules: -*,btrfs,i915` `strip: true`,
success with `modules: -*,btrfs,i915`,
success with `modules: -*,btrfs` `strip: true`,
fails if `/lib/modules/5.12.8-arch1-1/kernel/drivers/gpu/drm/i915/i915.ko.xz` is replaced with `i915.ko.xz` which doesn't have *bug_table. Other section is OK.

**Comment by anatol** [comment]
Interesting.. I am not aware of any reason why `bug_table` affects shutdown functionality.

For now we can just drop `*__bug_table` from the strip list.
