### ISSUE TITLE
non-portable?

### ISSUE THREAD

**Issue by dkwo** [anatol/booster#93]
This is just a question: is it possible to generate _portable_ initramfs with `booster`?

**Comment by anatol** [comment]
Could you please clarify your definition of "portable"? Is it "build image for different architecture (e.g. build arm image at x86)"? Or it maybe it means "build a universal image that works on majority x86 machines"? Or something else?

**Comment by dkwo** [comment]
I thought it means it can generate e.g. in the SVR4 with no CRC portable format, but let me double check.
Discussion was going on at https://github.com/void-linux/void-packages/issues/30813 hence my question.

**Comment by travankor** [comment]
I think they mean whether you can build booster with gcc-go (gcc backend for golang) since that supports more architectures.

**Comment by dkwo** [comment]
I misunderstood, here's what it meant:

gccgo is a joke/toy, and official go is only available on x86/arm/aarch64/ppc64le, so yeah, it's pretty non-portable

**Comment by travankor** [comment]
@dkwo I don't think there's anything actionable to do, so you should probably close this.

**Comment by dkwo** [comment]
I agree, it was only my ignorance :)
