### ISSUE TITLE
XanMod stuck on boot

### ISSUE THREAD

**Issue by dariox86** [anatol/booster#94]
With [linux-xanmod](https://aur.archlinux.org/packages/linux-xanmod/) on Parabola GNU/Linux-libre my system is stuck in the boot process. Of course it works with mkinitcpio. It just stops here:
![IMG20210731135509](https://user-images.githubusercontent.com/7864785/127739982-62967552-0bb8-4499-b6da-2c420f0c31f9.jpg)
I don't use a bootloader. I use efibootmgr to boot my system:
`# efibootmgr --bootnum 0 --disk /dev/nvme0n1 --create --label "Parabola GNU/Linux-libre" --loader /vmlinuz-linux-xanmod --unicode 'root=/dev/nvme0n1p2 rootflags=noatime,subvol=root initrd=\booster-linux-xanmod.img'`.
Feel free to indicate whatever log or information you may need if you are unable to reproduce the issue.

**Comment by anatol** [comment]
Thanks for the report.

Could you please enable debug mode for:
* Generator
* Booster boot

And post it's corresponding logs?

https://wiki.archlinux.org/title/Booster#Debug

**Comment by anatol** [comment]
Also please try enabling `universal` mode and see if it makes any difference for you.

**Comment by dariox86** [comment]
No difference with `universal` mode. Sorry, picture quality is poor.
[debug.log](https://github.com/anatol/booster/files/6911396/debug.log)
![IMG20210731170400](https://user-images.githubusercontent.com/7864785/127744761-175d5618-f439-4f69-80f6-40dc98e64d82.jpg)

**Comment by anatol** [comment]
There are some fixes at wip branch that might help with this issue. If you have a chance please pull the `wip` branch and check whether this issue is fixed or now.

**Comment by dariox86** [comment]
Sorry, WIP branch does not work, same output as in the first picture.

**Comment by anatol** [comment]
I just built xanmod kernel package 5.13.19 and run it in qemu with booster at btrfs root filesystem. This setup is pretty close to what you have. The tests pass without any issue, kernel boots to correctly to the userspace.

I see you using nvme for the root filesystem. Could you please add `modules: nvme` and regenerate booster image?

**Comment by anatol** [comment]
I debugged this problem a little bit more.

Indeed xanmod requires `nvme` driver in your case. I just added the module to default list and you don't need to configure it maually.

Another issue is that xanmod has an invalid `/dev/sr0` device by default and its read fails with 'no medium found' error. I added a fix for this issue as well.

The fixes are pushed to `wip` branch. Please take a look.

**Comment by dariox86** [comment]
Sorry, it doesn't work. At this point I am wondering if I am doing something wrong. I have downloaded the PKGBUILD from Arch Linux and saved it in a directory. From GitHub I have downloaded the WIP branch of Booster and saved it to a subdirectory src/booster-0.6. Finally in the directory with the PKGBUILD I issued `makepkg -si --noextract`. Of course I modified my EFI boot entry accordingly.

**Comment by anatol** [comment]
In my case I slightly modified the aur's PKGBUILD and added `#branch=wip` to the `sources`  https://gist.github.com/anatol/61920efe5327910d683d3d215fd7ecf9

It builds `booster-git-0.6.r34.gd07bc1e` for me.

**Comment by dariox86** [comment]
I apologize. Whatever I was doing wrong, now it works! Thank you! I look forward to replacing mkinitcpio with the latest stable release of Booster with these fixes merged.

**Comment by anatol** [comment]
These are great news!

Please keep testing booster with xanmod and report any issues you see. I'll test `wip` for a bit more and if everything is fine I'll merge it to `master`.

**Comment by dariox86** [comment]
Great. Thank you.
